language: node_js
node_js:
  - 8.0.0
sudo: required
services:
  - docker
before_install:
  - docker-compose -f components/services.yml up --build -d
  - sleep 100
  - chmod +x ./components/seed-data.sh
  - ./components/seed-data.sh